"""Initial migrations for models

Revision ID: 7fb655c2c16b
Revises: e6a5dac6149e
Create Date: 2025-03-27 03:14:53.210154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb655c2c16b'
down_revision = 'e6a5dac6149e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_option',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('qualification')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('qualification', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_option',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
